id: AC4160E45
base_file: fBD02.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:51:40.625088
  last_modified_at: 2022-06-05 19:51:40.625100
